name: "dbt_accounting_warehouse"
version: "1.0.0"
config-version: 2
require-dbt-version: ">=1.9.4"

profile: "default"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_accounting_warehouse:
    tier2_staging:
      +materialized: "table"
      +schema: "tier2_staging"
    tier3_domain:
      +materialized: "table"
      +schema: "tier3_domain"
    tier4_publishing:
      +materialized: "table"
      +schema: "tier4_publishing"
