name: testing

permissions:
  id-token: write 
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
      max-parallel: 1
    env: 
      PROJECT: ${{ secrets.PROJECT }}
      DESTINATION_TABLE: ${{ secrets.DESTINATION_TABLE }}
      DATASET: ${{ secrets.DATASET }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Fetch GCP Key
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          create_credentials_file: true
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT_PYTEST_EMAIL }}'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: dbt dry run
        run: |
          docker build --target devcontainer -t dbt .
          docker run --rm dbt dbt compile || exit 1
          docker run --rm dbt dbt-dry-run || exit 1