name: testing

permissions:
  contents: 'read'
  id-token: 'write'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
      max-parallel: 1
    env: 
      PROJECT: ${{ secrets.PROJECT }}
      DESTINATION_TABLE: ${{ secrets.DESTINATION_TABLE }}
      DATASET: ${{ secrets.DATASET }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build Docker image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v 4
        with:
          context: .
          file: Dockerfile
          tags: dbt:testing
          target: testing


      - name: Fetch GCP Key
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          create_credentials_file: true
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT_PYTEST_EMAIL }}'
      
      - name: Run pull request tests
        run: |
          set -e
          echo "Using credentials file at: $GOOGLE_APPLICATION_CREDENTIALS"
          docker run --rm \
            -v "$GOOGLE_APPLICATION_CREDENTIALS:/var/secrets/google/service-account.json:ro" \
            -e GOOGLE_APPLICATION_CREDENTIALS="/var/secrets/google/service-account.json" \
            dbt:testing
            